# Generated by Django 6.1 on 2026-08-12 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text='What we show the candidate')),
                ('rubric', models.TextField(help_text='What evidence we expect — sent to Gemini as the grading rubric, not shown to the candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scope', models.CharField(choices=[('base', 'Base'), ('company', 'Company-specific')], max_length=10)),
                ('required_level', models.PositiveSmallIntegerField(help_text='1-5')),
                ('description', models.TextField(blank=True)),
                ('assessed_in_demo', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'competencies',
                'ordering': ['scope', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(help_text='1-5, demonstrated level')),
                ('evidence', models.TextField(help_text='What in the answer supports this score')),
                ('gap_reason', models.TextField(blank=True, help_text='Empty if no gap')),
                ('raw_response', models.JSONField(blank=True, help_text='Full Gemini response, for debugging', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='core.assessmentanswer')),
            ],
        ),
        migrations.AddField(
            model_name='assessmentanswer',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.assessmenttask'),
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bio', models.TextField(blank=True)),
                ('education', models.TextField(blank=True, help_text='Formal, self-taught, bootcamp, career switch — whatever applies')),
                ('experience', models.TextField(blank=True)),
                ('projects', models.TextField(blank=True)),
                ('technologies', models.TextField(blank=True, help_text='Comma-separated or free text')),
                ('certifications', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assessmentanswer',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.candidate'),
        ),
        migrations.AddField(
            model_name='assessmenttask',
            name='competency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='core.competency'),
        ),
        migrations.CreateModel(
            name='DocumentationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_sources', to='core.competency')),
            ],
        ),
        migrations.CreateModel(
            name='LearningModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.competency')),
            ],
        ),
        migrations.CreateModel(
            name='LearningPathItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('reason', models.TextField(blank=True, help_text='Why this was included, e.g. from Gemini')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_items', to='core.candidate')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.learningmodule')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PracticeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('rubric', models.TextField()),
                ('competency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practice_task', to='core.competency')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('score_before', models.PositiveSmallIntegerField()),
                ('score_after', models.PositiveSmallIntegerField()),
                ('evidence', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_attempts', to='core.candidate')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.practicetask')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='core.assessmenttask')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CriterionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('met', 'Met'), ('partial', 'Partially demonstrated'), ('missing', 'Missing')], max_length=10)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_results', to='core.assessmentresult')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rubriccriterion')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='assessmentanswer',
            unique_together={('candidate', 'task')},
        ),
        migrations.CreateModel(
            name='LearningContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why_it_matters', models.TextField()),
                ('concept', models.TextField()),
                ('explanation', models.TextField()),
                ('example', models.TextField()),
                ('reasoning', models.TextField()),
                ('common_mistake', models.TextField()),
                ('key_knowledge', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_contents', to='core.candidate')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.competency')),
            ],
            options={
                'unique_together': {('candidate', 'competency')},
            },
        ),
    ]
